version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - onebox_network

  backend:
    build: ./backend
    container_name: onebox_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - IMAP_SERVER=${IMAP_SERVER}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      - elasticsearch
    networks:
      - onebox_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: onebox_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - onebox_network

networks:
  onebox_network:
    driver: bridge

volumes:
  elasticsearch_data: